services:
  db:
    image: postgres:15-alpine
    container_name: chat_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: chat_redis
    restart: always
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        UID: ${UID}
    container_name: chat_backend
    restart: always
    depends_on:
      - db
      - redis
    environment:
      WEB_HOST: ${WEB_HOST}
      WEB_PORT: ${WEB_PORT}
      DEBUG: ${DEBUG}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: ${DB_DRIVER}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}

      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}
      AUTH_ALGORITHM: ${AUTH_ALGORITHM}

      URL_SAVE_FILE: ${URL_SAVE_FILE}
      CHUNK_SIZE: ${CHUNK_SIZE}
      URL_STORAGE_LOCATION: ${URL_STORAGE_LOCATION}
    ports:
      - "8000:8000"
    volumes:
      - logs_data:/app/src/core/logs
      - files_data:/app/src/infrastructure/files_work/files
    networks:
      - app_network

volumes:
  logs_data:
  files_data:
  postgres_data:

networks:
  app_network:
